FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app
COPY WebApiJuros.csproj ./WebApiJuros/
COPY ["Domain/CalculoJuros.Domain/CalculoJuros.Domain.csproj", "Domain/CalculoJuros.Domain"]
RUN dotnet restore ./WebApiJuros/WebApiJuros.csproj
COPY ../ ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "WebApiJuros.dll" ]