name: Build and deploy container app to Azure Web App

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with: 
          registry: https://index.docker.io/v1/
          username: ${{ secrets.ContainerUserName }}
          password: ${{ secrets.ContainerPassword }}
        
      - name: Build and push container image to registry - WebApiCalculo
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.ContainerUserName }}/webapicalculo:${{ github.sha }}
          file: ./WebApiCalculo/WebApiCalculo/Dockerfile
          
      - name: Build and push container image to registry - WebApiJuros
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.ContainerUserName }}/webapijuros:${{ github.sha }}
          file: ./WebApiJuros/WebApiJuros/Dockerfile
          
  CD:
    runs-on: ubuntu-latest
    needs: CI
    environment:
      name: 'production'
      
    steps:
    - name: Deploy to Azure WebAPP - WebApiCalculo
      id: deploy-webapicalculo
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'WebApiCalculo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureWebApiCalculoPublishProfile }}
        images: 'index.docker.io/${{ secrets.ContainerUserName }}/webapicalculo:${{ github.sha }}'
        
    - name: Deploy to Azure WebAPP - WebApiJuros
      id: deploy-webapijuros
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'WebApiJuros'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureWebApiJurosPublishProfile }}
        images: 'index.docker.io/${{ secrets.ContainerUserName }}/webapijuros:${{ github.sha }}'

